### ISSUE TITLE
Issues Connecting to DEX

### ISSUE THREAD

**Issue by Liubov-crypto** [superhero-com/superhero-wallet#1464]
During testing DEX, I had problems connecting the wallet, it periodically failed (some network issues):
![error wallet login ](https://user-images.githubusercontent.com/69896204/171997376-785f61b4-a2f5-4481-ab92-b3e9c238b12e.png)

also, the pop-up opens not in the web wallet, but on the Dex page:
https://user-images.githubusercontent.com/69896204/171997383-7a6dbd85-c019-44dd-9ceb-94f47403cd25.mov

When testing, I experienced constant problems with sh wallet:
![errr](https://user-images.githubusercontent.com/69896204/172001340-173592c7-89d0-47ba-8fb1-09cc73ec06d9.png)

**Comment by CedrikNikita** [comment]
That is mostly the DEX issue, should be fixed on their side.

**Comment by Liubov-crypto** [comment]
After connecting the wallet to the dex, it works on the main network, although the wallet uses the testnet:
https://dex.prd.aepps.com/swap

The errors described above are reproduced. 

Then the network itself switches to the test one and the dex works fine. 

Then I didn’t use dex for a while and it spontaneously returned to the main network and connection errors began to reproduce again.

**Comment by Liubov-crypto** [comment]
Still reproducible on dev branch https://github.com/aeternity/superhero-wallet/commit/e7028cdb3de7f8bce30922404ec58699f144d4a2: After connecting the wallet to the dex, it works on the main network, although the wallet uses the testnet

**Comment by CedrikNikita** [comment]
This issue should be fixed on the DEX side. Wallet sends current `networkId` in the callback URL.
