### ISSUE TITLE
ui: support ERC-20 in transaction history

### ISSUE THREAD

**Issue by peronczyk** [superhero-com/superhero-wallet#2531]
**Acceptance criteria:**

Includes the following:
- transaction history on the Ethereum account detail page
- transaction history in the Latest transactions widget

**Comment by Liubov-crypto** [comment]
1. The ERC-20 tokens transactions could disappear from time to time from The Latest Tx widget and from the transaction history on the Ethereum account detail page. I have to refresh the page to see them: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/00893c99-9863-440e-9e2a-cac397372572


https://github.com/superhero-com/superhero-wallet/assets/69896204/1683bbbb-59dc-483a-99a4-41b33b74b2fa


2. Also the Transaction list could be not fully shown on ETH account detail page. 

3. Idk, if it's related to this task, but ERC-20 Txs are also displaying on coins/ethereum page in Transaction list because fee is paid in ETH: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/89cca758-2d4f-4550-89f6-75c06ee501f2

4. The ERC-20 transactions could be displaying in The Latest Tx widget as ETH Tx from time to time (fee is paid in ETH). I have to refresh page to see them correctly: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/555a5d64-ae5e-4366-b1cc-ef5e7072576f

**Comment by Liubov-crypto** [comment]
Besides the issue that Nikita found, I discovered next: 

1. I can see transactions from testnet in mainnet when I'm switching the network:

https://github.com/superhero-com/superhero-wallet/assets/69896204/36c41bd2-201b-4e05-81e8-fc51e33ee40a

2. Maybe it's glitch but I see the same transaction twice in Tx list: 

![2 times ](https://github.com/superhero-com/superhero-wallet/assets/69896204/e03ec6f9-cdbb-4238-8646-6db9067a6b13)

3. The extension is starting "jumping" when I'm trying to reach out the end of Tx list: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/0aa7ffd8-3c96-4799-9576-05469b4c3f00

Not an issue, rather question: 

is this new option? this text at the bottom when I've reached out the end of Tx list? 

![upd](https://github.com/superhero-com/superhero-wallet/assets/69896204/ec3af920-9973-457e-ba4b-5d5b55987088)

**Comment by peronczyk** [comment]
I fixed mentioned issues @Liubov-crypto . Can you please retest?
Regarding the last thing: the message in the end of the list: yes, this was discussed with Tsvetan. Sorry for not letting you aut about this new thing.

**Comment by Liubov-crypto** [comment]
1. I can see transactions from testnet in mainnet when I'm switching the network - still reproducible for me: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/b52ad35e-68c1-40c7-88a3-3ee2a5312c6b

2. Issue with displaying amount of "allow ae usage" : 

![tok](https://github.com/superhero-com/superhero-wallet/assets/69896204/cde31626-6192-414b-97ad-f1dd81b4f5fb)

The rest issues have been fixed.

**Comment by peronczyk** [comment]
The issue for the transactions from testnet visible in mainnet is another thing related to the fact that we are using free version of ETH API. If user changes the network and the API reaches the maximum call amount the app is trying to avoid clearing the transaction list. This feature is related to @martinkaintas work. Until we have fully working API these kind of glitches will happen. Here's separate task for this: https://github.com/orgs/superhero-com/projects/2/views/2?pane=issue&itemId=52383948

Regarding the allowance amount calculation I also created separate task for this: https://github.com/orgs/superhero-com/projects/2/views/2?pane=issue&itemId=52386501

Do we have any other issues found there?

**Comment by peronczyk** [comment]
The first recent issue is fixed (I hope).
Regarding the second one I think someone was working on this in a separate PR. I'll ask. But in short: this is not caused by my PR.

**Comment by Liubov-crypto** [comment]
You are correct, the ERC-20 Txs and ETH Txs are fetching (in pending status) approx 10 min...

but the list of Txs looks good to me in the web wallet. 

In extension I can't see the Tx list from time to time, or could be reproducible the error with seeing only ERC-20 in the Tx list or ETH, as I described above. Idk from what it depends on...


https://github.com/superhero-com/superhero-wallet/assets/69896204/f4a79e96-2df1-4a4b-969c-fe0cb1edba71



https://github.com/superhero-com/superhero-wallet/assets/69896204/a0f7e9c0-8ae9-4615-91ad-2fa76d43ab9e

**Comment by Liubov-crypto** [comment]
We can proceed with this pr. 

I created a separate issue about strange behaviour in Tx list in extension: #2703
